[tool.poetry]
name = "flask-vuejs"
version = "0.1.0"
description = "Connect Flask With VueJS Framework"
authors = ["Marcus Pereira <mpereirassa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.1"
flask-assets = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-selenium = "^1.17.0"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
